### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by drtshock** [stefvanschie/buildinggame#196]
Curious why the plugin is compiling on Java 11?

https://github.com/stefvanschie/buildinggame/blob/master/buildinggame/pom.xml#L162

**Comment by stefvanschie** [comment]
Java 11 is the latest LTS release of Java and I was under the impression that Java 8 support would have reached / be reaching it's end of life soon, although I think OpenJDK extended the support to September 2023 (I don't really track that stuff too well if I'm being honest). Either way, I prefer to use the latest LTS release, mainly because of the feature additions it brings.

**Comment by anemul** [comment]
Java 11 breaks just about all my other plugins . Was really excited to see your plugin updated to work on 1.14 , but this really bummed that excitement real quick :(

**Comment by drtshock** [comment]
Here's a java 8 fork https://github.com/Minehut/buildinggame though I haven't merged from upstream in awhile.

**Comment by stefvanschie** [comment]
Considering the plugin is now using Java 17 and the latest server versions that are supported also require at least Java 17, this shouldn't be an issue.
