### ISSUE TITLE
Tasks lag

### ISSUE THREAD

**Issue by WolfMaster333** [stefvanschie/buildinggame#4]
Hello, The hologram update task and the win timer task are putting load on our server according to the timing reports.Can you please try to fix that.Thanks a lot in advance.

**Comment by stefvanschie** [comment]
I think I found what was making the scoreboard lag. The comparison between before I changed it and after I changed it:

             Pct Total | Pct Tick | Total  | Avg      
Before: 0.16%     | 3.44%   | 0.24s | 1.72ms
After:    0.09%     | 1.85%   | 0.13s | 0.92ms

For the win timer, I have no idea what is causing it to lag so much, because it does absolutely nothing.

**Comment by WolfMaster333** [comment]
Thanks so much. Please let me know when is this going to be release so we can test and report back

**Comment by stefvanschie** [comment]
I made a new version (2.1.0) and this issue is fixed.
