### ISSUE TITLE
get started >> help me pls.

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#45]
spigot 1.11.2
bungee latest

0. why plugin have 2 copied same params in config and in arena? That make plugin work wrongly and i dont know why ure did that cuz commands change one file but game use other file for that params. that confuse and make work with plugin terrible (+ other badly things)

config.yml
timer: 300
votetimer: 15
waittimer: 60
wintimer: 10

arenas.yml
  timer: 300
  lobby-timer: 60
  vote-timer: 15
  win-timer: 15

WTF?

1. spigot addon 1.11 work wrong - signs not refresh info from config
i delete that sockets and addon and using bungeesigns now.

2. where vote subject permission? only OP can vote subjects before match start ><

3. statistic - using mysql. i dont understand plugin sting in config. i have mysql stats and file stats.yml why they two still updating?

4. scorboard working wrongly - that not refreshing if i reload /bg reload and that show different stats of sign stats. why???? how fix that?

5. if restart server - sign stats will show crazy info like -1 insted of some 4032 block broken. what stats showing your plugin? per session? daily? weekly? monthly? all time? why that crashed after restart server?

6. half of default commands like winner fireworks not working (like execute something) and i cant using plugin commands to give winner some usefull reward. why?

7. why ure have not сurrent full information page about list of permissions?

8. how i can customize what options have different groups in option menu, like default have 2 pages of heads, vip have only 3 particals of all list, etc

9. can ure pls stop adding new featurs and work about stable what ure already made?
i think ure dont need bungee/spigot addon, we have many other stable ways to move players trough servers like bungeesigns bungeeportals etc.

10. and i think ure should make what ure have now - stable and do that plugin premium. like 10 $

**Comment by stefvanschie** [comment]
1.  That may have something to do with the error you showed me earlier on dev.bukkit.org.
2.  The permission is _bg.subjectmenu_. I also made the commands & permissions table more visible on spigotmc.org, so hopefully, it'll now be easier to look for permissions.
3.  In the config.yml the parts within <> should be replaced by the correct information. E.g. <user> should be replaced with the database username, <database> with the database name and <password> with your database password. Also, the plugin will fall back to file saving if the database fails to work.
4.  That appears to be a bug, I'll fix it in the next version.
5.  Same bug as 4, will be fixed in the next version.
6.  The entity names were changed in 1.11, change the ones in the command to the new ones.
7.  I've added the permissions to the page and made it easier to read them.
8.  There's currently no way to do that, I'll add that in the next version.
9.  Bugs which are reported to me are most of the time fixed in the next version (unless it's a bug with the spigot/bungeecord software or other plugins). Small features which are requested will be added with the bug fixes. Bigger features are added when I don't receive a lot of bug reports after the release of the previous version.
10. I'm not planning on making my plugin premium, as that would mean that I have to release three other plugins for free, I would have to handle stuff like chargebacks and cracked/leaked versions and I would have to remove my plugin from dev.bukkit.org (and there are some other reasons). I'll keep my resource free, at least for now.

**Comment by BabelSolea** [comment]
2. thatnks cuz miniature of pic was not open to fullsize - was not clickable
3. ok will check it
6. oh thanks for that tip! i forget about it
other - ok. done)

ok) when ure release new version with fixed scoreboard and stats (i still dont know why after reload plugin or restart server i see on signs diffent stats of all params and i dont know from that new stats taken) i will donate ure on 10$ cuz i think that good price per good plugin minigame =)

on mysql i have some like 70 players stats but on stats.yml only 6 players. how do to file and mysql have same data?
